- name: Uninstall old versions
  yum:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine

- name: Download script from official Docker
  get_url:
    url: https://get.docker.com/
    dest: /tmp/docker_install.sh
    owner: "root"
    group: "root"
    mode: 0600

- name: Run the install Docker script.
  shell: sh VERSION={{ docker_version }} /tmp/docker_install.sh
  register: docker_install

- debug:
  var: docker_install
